// <auto-generated />
using CIS174TrevorStewart.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OlympicsProject.Migrations
{
    [DbContext(typeof(OlympicsContext))]
    partial class OlympicsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIS174TrevorStewart.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryId");

                    b.HasIndex("SportName");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Flag = "Images/canada.jpg",
                            Name = "Canada",
                            SportName = "Curling"
                        },
                        new
                        {
                            CountryId = 2,
                            Flag = "Images/sweden.jpg",
                            Name = "Sweden",
                            SportName = "Curling"
                        },
                        new
                        {
                            CountryId = 3,
                            Flag = "Images/great_britain.jpg",
                            Name = "Great Britain",
                            SportName = "Curling"
                        },
                        new
                        {
                            CountryId = 4,
                            Flag = "Images/jamaica.jpg",
                            Name = "Jamaica",
                            SportName = "Bobsleigh"
                        },
                        new
                        {
                            CountryId = 5,
                            Flag = "Images/italy.jpg",
                            Name = "Italy",
                            SportName = "Bobsleigh"
                        },
                        new
                        {
                            CountryId = 6,
                            Flag = "Images/japan.jpg",
                            Name = "Japan",
                            SportName = "Bobsleigh"
                        },
                        new
                        {
                            CountryId = 7,
                            Flag = "Images/germany.jpg",
                            Name = "Germany",
                            SportName = "Diving"
                        },
                        new
                        {
                            CountryId = 8,
                            Flag = "Images/china.jpg",
                            Name = "China",
                            SportName = "Diving"
                        },
                        new
                        {
                            CountryId = 9,
                            Flag = "Images/mexico.jpg",
                            Name = "Mexico",
                            SportName = "Diving"
                        },
                        new
                        {
                            CountryId = 10,
                            Flag = "Images/brazil.jpg",
                            Name = "Brazil",
                            SportName = "Road Cycling"
                        },
                        new
                        {
                            CountryId = 11,
                            Flag = "Images/netherlands.jpg",
                            Name = "Netherlands",
                            SportName = "Road Cycling"
                        },
                        new
                        {
                            CountryId = 12,
                            Flag = "Images/united_states.jpg",
                            Name = "USA",
                            SportName = "Road Cycling"
                        },
                        new
                        {
                            CountryId = 13,
                            Flag = "Images/thailand.jpg",
                            Name = "Thailand",
                            SportName = "Archery"
                        },
                        new
                        {
                            CountryId = 14,
                            Flag = "Images/uruguay.jpg",
                            Name = "Uruguay",
                            SportName = "Archery"
                        },
                        new
                        {
                            CountryId = 15,
                            Flag = "Images/ukraine.jpg",
                            Name = "Ukraine",
                            SportName = "Archery"
                        },
                        new
                        {
                            CountryId = 16,
                            Flag = "Images/austria.jpg",
                            Name = "Austria",
                            SportName = "Canoe Sprint"
                        },
                        new
                        {
                            CountryId = 17,
                            Flag = "Images/pakistan.jpg",
                            Name = "Pakistan",
                            SportName = "Canoe Sprint"
                        },
                        new
                        {
                            CountryId = 18,
                            Flag = "Images/zimbabwe.jpg",
                            Name = "Zimbabwe",
                            SportName = "Canoe Sprint"
                        },
                        new
                        {
                            CountryId = 19,
                            Flag = "Images/france.jpg",
                            Name = "France",
                            SportName = "Breakdancing"
                        },
                        new
                        {
                            CountryId = 20,
                            Flag = "Images/cyprus.jpg",
                            Name = "Cyprus",
                            SportName = "Breakdancing"
                        },
                        new
                        {
                            CountryId = 21,
                            Flag = "Images/russia.jpg",
                            Name = "Russia",
                            SportName = "Breakdancing"
                        },
                        new
                        {
                            CountryId = 22,
                            Flag = "Images/finland.jpg",
                            Name = "Finland",
                            SportName = "Skateboarding"
                        },
                        new
                        {
                            CountryId = 23,
                            Flag = "Images/slovakia.jpg",
                            Name = "Slovakia",
                            SportName = "Skateboarding"
                        },
                        new
                        {
                            CountryId = 24,
                            Flag = "Images/portugal.jpg",
                            Name = "Portugal",
                            SportName = "Skateboarding"
                        });
                });

            modelBuilder.Entity("CIS174TrevorStewart.Models.Sport", b =>
                {
                    b.Property<string>("SportName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportName");

                    b.ToTable("Sport");

                    b.HasData(
                        new
                        {
                            SportName = "Curling",
                            Category = "Winter Olympics",
                            Type = "Indoor"
                        },
                        new
                        {
                            SportName = "Bobsleigh",
                            Category = "Winter Olympics",
                            Type = "Outdoor"
                        },
                        new
                        {
                            SportName = "Diving",
                            Category = "Summer Olympics",
                            Type = "Indoor"
                        },
                        new
                        {
                            SportName = "Road Cycling",
                            Category = "Summer Olympics",
                            Type = "Outdoor"
                        },
                        new
                        {
                            SportName = "Archery",
                            Category = "Paralympics",
                            Type = "Indoor"
                        },
                        new
                        {
                            SportName = "Canoe Sprint",
                            Category = "Paralympics",
                            Type = "Outdoor"
                        },
                        new
                        {
                            SportName = "Breakdancing",
                            Category = "Youth Olympic Games",
                            Type = "Indoor"
                        },
                        new
                        {
                            SportName = "Skateboarding",
                            Category = "Youth Olympic Games",
                            Type = "Outdoor"
                        });
                });

            modelBuilder.Entity("CIS174TrevorStewart.Models.Country", b =>
                {
                    b.HasOne("CIS174TrevorStewart.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });
#pragma warning restore 612, 618
        }
    }
}
