// <auto-generated />
using CIS174TrevorStewart.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIS174TrevorStewart.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIS174TrevorStewart.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Trevor",
                            Grade = "A",
                            LastName = "Stewart"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Amber",
                            Grade = "A",
                            LastName = "Lang"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Steve",
                            Grade = "B",
                            LastName = "Bobber"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Chuck",
                            Grade = "A-",
                            LastName = "Tingle"
                        },
                        new
                        {
                            StudentId = 5,
                            FirstName = "Cody",
                            Grade = "C",
                            LastName = "Phish"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
